from django.shortcuts import render, get_object_or_404
from django.http import FileResponse, Http404
from core.models import ToolRun, ToolRunFile
from core.decorators import staff_required
from core.models import ToolRunFile
from django.core.files.base import ContentFile
import os
from django.shortcuts import redirect


@staff_required
def download_file(request, file_id):
    f = get_object_or_404(ToolRunFile, pk=file_id)
    if not f.file:
        raise Http404("File not available.")

    from core.models import UserProfile
    profile, _ = UserProfile.objects.get_or_create(user=request.user)
    tool_map = {
        'COF': 'cof',
        'MORNING': 'morning',
        'PENDENCY': 'pendency',
        'PREV_MONTH': 'prev_month',
        'BTPL': 'btpl',
        'ATTENDANCE': 'attendance',
    }
    required_perm = tool_map.get(f.run.tool)
    if required_perm and not getattr(profile, f"can_use_{required_perm}", False):
        messages.error(request, f"You do not have permission to download files generated by the {f.run.get_tool_display()} tool.")
        return redirect('dashboard')

    return FileResponse(f.file.open('rb'), as_attachment=True,
                        filename=f.download_name or os.path.basename(f.file.name))


@staff_required
def tool_result(request, pk):
    run = get_object_or_404(ToolRun.objects.prefetch_related('files'),
                            pk=pk, status=ToolRun.STATUS_SUCCESS)
    active = {'COF': 'cof', 'MORNING': 'morning', 'PENDENCY': 'pendency', 'PREV_MONTH': 'prev_month'}.get(run.tool, '')

    # Check permissions
    from core.models import UserProfile
    profile, _ = UserProfile.objects.get_or_create(user=request.user)
    if active and not getattr(profile, f"can_use_{active}", False):
        messages.error(request, f"You do not have permission to view results for the {run.get_tool_display()} tool.")
        return redirect('dashboard')

    return render(request, 'core/portal/tool_result.html', {'active': active, 'run': run})


