# Generated by Django 6.0.6 on 2026-06-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cofworkbook_toolrunfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrunfile',
            name='download_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
