# Generated by Django 6.0.6 on 2026-06-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_toolrunfile_download_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolrun',
            name='tool',
            field=models.CharField(choices=[('COF', 'COF Generator'), ('MORNING', 'Morning Report'), ('PENDENCY', 'Pendency Report'), ('PREV_MONTH', 'Previous Month Update')], max_length=20),
        ),
    ]
