# Generated by Django 6.0.6 on 2026-06-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolrun',
            name='tool',
            field=models.CharField(choices=[('COF', 'COF Generator'), ('MORNING', 'Morning Report'), ('PENDENCY', 'Pendency Report'), ('PREV_MONTH', 'Previous Month Update'), ('BTPL', 'BTPL Sheet')], max_length=20),
        ),
    ]
