# Generated by Django 6.0.6 on 2026-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_btplworkbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_use_btpl',
            field=models.BooleanField(default=True),
        ),
    ]
