# Generated by Django 6.0.6 on 2026-06-15 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_can_use_btpl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_use_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='toolrun',
            name='tool',
            field=models.CharField(choices=[('COF', 'COF Generator'), ('MORNING', 'Morning Report'), ('PENDENCY', 'Pendency Report'), ('PREV_MONTH', 'Previous Month Update'), ('BTPL', 'BTPL Sheet'), ('ATTENDANCE', 'Attendance Tracker')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceWorkbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attendance/')),
                ('original_name', models.CharField(max_length=255)),
                ('active_sheet', models.CharField(default='JUNE 2026', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_workbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
