# Generated by Django 6.0.6 on 2026-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employeesalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255, unique=True)),
                ('adhoc_salary_increase_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage (e.g. 25.00 for 25%)', max_digits=5)),
                ('adhoc_allowance_monthly_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lwf', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_rate_per_day', models.DecimalField(decimal_places=2, default=492.12, max_digits=10)),
                ('sp_allowance_rate_per_day', models.DecimalField(decimal_places=2, default=96.58, max_digits=10)),
                ('standard_month_days', models.IntegerField(default=26)),
                ('other_allowance_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage (e.g. 10.00)', max_digits=5)),
                ('other_allowance_eligible_departments', models.CharField(default='CV-SUPERVISOR,CV-DEO', help_text='Comma-separated list of departments', max_length=255)),
                ('hra_pct', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage (e.g. 5.00)', max_digits=5)),
                ('leave_payment_threshold_days', models.DecimalField(decimal_places=2, default=19.9, max_digits=5)),
                ('leave_payment_amount', models.DecimalField(decimal_places=2, default=589.0, max_digits=10)),
                ('extra_day_rate', models.DecimalField(decimal_places=2, default=589.0, max_digits=10)),
                ('pf_wage_ceiling', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('pf_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Percentage (e.g. 12.00)', max_digits=5)),
                ('esic_employee_rate', models.DecimalField(decimal_places=2, default=0.75, help_text='Percentage (e.g. 0.75)', max_digits=5)),
                ('pt_slab_1_max', models.DecimalField(decimal_places=2, default=7499.0, max_digits=10)),
                ('pt_slab_2_max', models.DecimalField(decimal_places=2, default=9999.0, max_digits=10)),
                ('pt_slab_3_amount', models.DecimalField(decimal_places=2, default=300.0, help_text='Usually 200, but 300 in Feb', max_digits=10)),
                ('canteen_rate_per_day', models.DecimalField(decimal_places=2, default=14.0, max_digits=10)),
                ('reporting_pf_cost_rate', models.DecimalField(decimal_places=2, default=25.0, help_text='Percentage (e.g. 25.00)', max_digits=5)),
                ('reporting_esic_cost_rate', models.DecimalField(decimal_places=2, default=4.0, help_text='Percentage (e.g. 4.00)', max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
