# Generated by Django 6.0.6 on 2026-06-28 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_userprofile_can_use_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendanceworkbook',
            index=models.Index(fields=['is_active'], name='core_attend_is_acti_05d149_idx'),
        ),
        migrations.AddIndex(
            model_name='btplworkbook',
            index=models.Index(fields=['is_active'], name='core_btplwo_is_acti_1c44df_idx'),
        ),
        migrations.AddIndex(
            model_name='cofworkbook',
            index=models.Index(fields=['is_active'], name='core_cofwor_is_acti_d40ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='ftlworkbook',
            index=models.Index(fields=['is_active'], name='core_ftlwor_is_acti_280c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='toolrun',
            index=models.Index(fields=['tool', '-created_at'], name='core_toolru_tool_cc29a0_idx'),
        ),
    ]
