# Generated by Django 6.0.6 on 2026-06-29 19:10

from django.db import migrations

def sanitize_workbooks(apps, schema_editor):
    for model_name in ['CofWorkbook', 'BtplWorkbook', 'AttendanceWorkbook', 'FtlWorkbook']:
        Model = apps.get_model('core', model_name)
        active_instances = Model.objects.filter(is_active=True).order_by('-uploaded_at')
        if active_instances.count() > 1:
            keep_active = active_instances.first()
            Model.objects.filter(is_active=True).exclude(pk=keep_active.pk).update(is_active=False)

def reverse_sanitize(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_attendanceworkbook_core_attend_is_acti_05d149_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(sanitize_workbooks, reverse_sanitize),
    ]
