# Generated by Django 6.0.6 on 2026-06-29 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sanitize_active_workbooks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendanceworkbook',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_attendance'),
        ),
        migrations.AddConstraint(
            model_name='btplworkbook',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_btpl'),
        ),
        migrations.AddConstraint(
            model_name='cofworkbook',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_cof'),
        ),
        migrations.AddConstraint(
            model_name='ftlworkbook',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_ftl'),
        ),
    ]
