# Generated by Django 6.0.6 on 2026-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customer_driver_migrationfeatureflags_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('shipment_type', 'source_key'), name='unique_shipment_source_key'),
        ),
    ]
