# Generated by Django 6.0.6 on 2026-07-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
    ]
