# Generated by Django 6.0.6 on 2026-07-04 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_data_migration_attendance_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='driver',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.employee'),
        ),
    ]
