# Generated by Django 6.0.6 on 2026-08-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_attendancerecord_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceworkbook',
            name='file',
            field=models.FileField(max_length=500, upload_to='attendance/'),
        ),
        migrations.AlterField(
            model_name='btplworkbook',
            name='file',
            field=models.FileField(max_length=500, upload_to='btpl/'),
        ),
        migrations.AlterField(
            model_name='cofworkbook',
            name='file',
            field=models.FileField(max_length=500, upload_to='cof/'),
        ),
        migrations.AlterField(
            model_name='ftlworkbook',
            name='file',
            field=models.FileField(max_length=500, upload_to='ftl/'),
        ),
        migrations.AlterField(
            model_name='toolrun',
            name='output_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='tool_outputs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='toolrunfile',
            name='file',
            field=models.FileField(max_length=500, upload_to='tool_outputs/%Y/%m/'),
        ),
    ]
