import os
import requests
from django.core.files.storage import Storage

class VercelBlobStorage(Storage):
    """
    A custom Django storage backend for Vercel Blob using requests.
    Relies on the BLOB_READ_WRITE_TOKEN environment variable.
    """
    def __init__(self, **kwargs):
        self.token = os.environ.get('BLOB_READ_WRITE_TOKEN')
        if not self.token:
            raise ValueError("BLOB_READ_WRITE_TOKEN environment variable is not set")
        self.api_url = "https://blob.vercel-storage.com"

    def _save(self, name, content):
        """
        Saves the file to Vercel Blob and returns the absolute URL.
        """
        file_bytes = content.read()
        headers = {
            "Authorization": f"Bearer {self.token}",
            "x-api-version": "7",
            "x-add-random-suffix": "1"
        }
        
        # Try uploading with default (public) access
        response = requests.put(
            f"{self.api_url}/{name}",
            data=file_bytes,
            headers=headers
        )
        
        # If the store is private, the API will reject public uploads
        if response.status_code == 400:
            error_msg = response.json().get("error", {}).get("message", "")
            if "private store" in error_msg:
                # Retry with private access
                headers["x-vercel-blob-access"] = "private"
                response = requests.put(
                    f"{self.api_url}/{name}",
                    data=file_bytes,
                    headers=headers
                )
                
        response.raise_for_status()
        resp_data = response.json()
        
        # Return the absolute URL generated by Vercel Blob
        return resp_data.get("url", name)

    def url(self, name):
        """
        Since _save() returns the absolute URL, `name` is already the URL.
        """
        return name

    def _open(self, name, mode='rb'):
        """
        Fetches the file from Vercel Blob into memory.
        `name` is expected to be the full URL.
        """
        headers = {
            "Authorization": f"Bearer {self.token}",
            "x-api-version": "7"
        }
        response = requests.get(name, headers=headers)
        response.raise_for_status()
        
        from django.core.files.base import ContentFile
        return ContentFile(response.content, name=name)

    def exists(self, name):
        return False

    def delete(self, name):
        if name and name.startswith('http'):
            try:
                headers = {
                    "Authorization": f"Bearer {self.token}",
                    "x-api-version": "7"
                }
                requests.post(
                    f"{self.api_url}/delete",
                    json={"urls": [name]},
                    headers=headers
                )
            except Exception:
                pass
